title_name = "Perfect Dark"
title_id = "584109C2" #
hash = "F11821D5051987EE" # default.xex
#media_id = "00000000"

[[patch]]
    name = "Fix FogNearFar"
    desc = "Change FogNearFar register in shader"
    author = "Adrian"
    is_enabled = true

    [[patch.be8]]
        address = 0x82014B9B
        value = 0x30
